pom.xml
- 레포지토리: jitpack 추가
- 디펜던시: iamport추가
- 없음
- 폼추가
=> feat: 디펜던시 추가

src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- servlet-context 추가
- messageSource errors 부분 추가
- 없음
=> feat : servlet-context 추가

src/main/java/org/hermez/member/controller/MemberController.java, src/main/java/org/hermez/member/dto/MemberRegisterRequest.java, src/main/java/org/hermez/member/dto/MemberRegisterResponse.java, src/main/java/org/hermez/member/mapper/MemberMapper.java, src/main/java/org/hermez/member/model/Member.java, src/main/java/org/hermez/member/model/MemberRepository.java, src/main/java/org/hermez/member/service/MemberService.java, src/main/java/org/hermez/member/service/impl/MemberServiceImpl.java, src/main/resources/errors.properties
- 회원가입 구현
- 회원가입 및 유효성 처리
- 없습니당.
=> feat : 회원가입 구현

pom.xml, src/main/java/org/hermez/member/controller/MemberController.java, src/main/java/org/hermez/member/mapper/MemberMapper.java, src/main/java/org/hermez/member/model/MemberRepository.java, src/main/java/org/hermez/member/service/MemberService.java, src/main/java/org/hermez/member/service/impl/MemberServiceImpl.java, src/main/webapp/WEB-INF/spring/root-context.xml
- 회원가입 버그 수정
- 회원가입 및 유효성 처리 버그 수정
- pom.xml - validation 의존성 추가
- root-context.xml - member.mapper 추가
- 멤버 버그 수정했습니다. 파일 돌아갑니다.
=> fix : 회원가입 버그 수정

src/main/webapp/WEB-INF/views/flone/css.jsp, src/main/webapp/WEB-INF/views/flone/footer.jsp, src/main/webapp/WEB-INF/views/flone/header.jsp, src/main/webapp/WEB-INF/views/flone/index.jsp, src/main/webapp/WEB-INF/views/flone/script.jsp
- jsp layout 추가
- header , footer , index , css , js 공통 JSP 추가
- 레이아웃 설정 했습니다. pull 받아서 문제 생기면 얘기해주세요
=> feat: jsp layout 기능 추가

src/main/java/org/hermez/reservation/model/Reservation.java
- feature : reservation 모델 작성
- Reservation 클래스 작성
- reservation 도메인 만듬
=> feature : reservation 모델 작성

src/main/java/org/hermez/member/dto/MemberLoginRequest.java
- 회원가입 로그인
- 회원가입 로그인 구현
- 오류 및 로그인 구현했습니당
=> feat : 회원가입 로그인

src/main/java/org/hermez/member/dto/MemberResponse.java, src/main/java/org/hermez/member/dto/MyAccountResponse.java
=> fix : 로그인 버그

src/main/java/org/hermez/paymenthistory/model/PaymentHistory.java
- feature : paymenthistory 모델 작성
- feature/paymenthistory/model
- PaymentHistory.java 작성
- 결제기록 도메인 작성
=> feature : paymenthistory 모델 작성

src/main/java/org/hermez/reservation/mapper/ReservationMapper.java, src/main/java/org/hermez/reservation/model/ReservationRepository.java, src/main/java/org/hermez/reservation/model/impl/ReservationRepositoryImpl.java, src/main/webapp/WEB-INF/spring/root-context.xml
- reservation/model 모델 추가
- ReservationMapper.java
- ReservationRepository
- ReservationRepositoryImpl
- root-context.xml -> reservationMapper 위치 추가
- 해당내용들 추가
=> feature : reservation/model 모델 추가

src/main/webapp/WEB-INF/spring/root-context.xml
- servlet-context.xml 에 매퍼 등록
- 누락된 매퍼 classroom, image context에  추가
- 바로 수정했습니다!
=> servlet-context.xml 에 매퍼 등록

src/main/java/org/hermez/paymenthistory/dto/CancelDTO.java, src/main/java/org/hermez/reservation/service/IamportService.java
- 결제API( 아임포트 ) 관련 클래스 추가
- 결제API( 아임포트 ) 관련 클래스 추가
- IamportService 결제API 이용 로직
- CancelDTO 결제 취소시 요청 데이터
- 변경 내용과 같음
=> feature : 결제API( 아임포트 ) 관련 클래스 추가

src/main/java/org/hermez/paymenthistory/service/payapi/IamportService.java
- 결제API( 아임포트 ) 관련 클래스 위치 이동
- paymenthistory 패키지의 서비스로 이동
- 변경 내용과 같음
=> rename : 결제API( 아임포트 ) 관련 클래스 위치 이동

src/main/java/org/hermez/classroom/board/controller/BoardController.java, src/main/java/org/hermez/classroom/board/dto/BoardEditRequest.java, src/main/java/org/hermez/classroom/board/dto/BoardRegisterRequest.java, src/main/java/org/hermez/classroom/board/mapper/BoardMapper.java, src/main/java/org/hermez/classroom/board/model/Board.java, src/main/java/org/hermez/classroom/board/service/BoardService.java, src/main/java/org/hermez/classroom/board/service/impl/BoardServiceImpl.java, src/main/java/org/hermez/classroom/reply/controller/ReplyController.java, src/main/java/org/hermez/classroom/reply/dto/ReplyRegisterRequest.java, src/main/java/org/hermez/classroom/reply/mapper/ReplyMapper.java, src/main/java/org/hermez/classroom/reply/model/Reply.java, src/main/java/org/hermez/classroom/reply/service/ReplyService.java, src/main/java/org/hermez/classroom/reply/service/impl/ReplyServiceImpl.java
- 클래스룸 내부 게시판-댓글 MVC 구현
- 게시판 board [ Controller, Service, Mapper, Model ] 구현
- 댓글 reply [ Controller, Service, Mapper, Model ] 구현
- context 파일을 수정하지 않았습니다 jsp 파일이랑 빠르게 올리겠습니다.
=> 클래스룸 내부 게시판-댓글 MVC 구현

src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/flone/board-detail.jsp, src/main/webapp/WEB-INF/views/flone/board-edit-form.jsp, src/main/webapp/WEB-INF/views/flone/board-list.jsp, src/main/webapp/WEB-INF/views/flone/board-register-form.jsp, src/main/webapp/WEB-INF/views/flone/class-room-list.jsp, src/main/webapp/WEB-INF/views/flone/classroom-register-form.jsp
- 클래스룸, 게시판 JSP 추가
- 클래스룸 상세페이지, 리스트 페이지, 게시판 리스트페이지, 상세페이지, 수정페이지 추가
- context.xml 에 mapper 추가
- 실행시 문제 없습니다ㅎㅎ
=> 클래스룸, 게시판 JSP 추가

src/main/java/org/hermez/classroom/board/controller/BoardController.java, src/main/java/org/hermez/classroom/board/model/Board.java, src/main/java/org/hermez/classroom/classroom/controller/ClassroomController.java, src/main/java/org/hermez/classroom/reply/controller/ReplyController.java, src/main/webapp/WEB-INF/views/flone/board-detail.jsp, src/main/webapp/WEB-INF/views/flone/board-edit-form.jsp, src/main/webapp/WEB-INF/views/flone/board-list.jsp, src/main/webapp/WEB-INF/views/flone/board-register-form.jsp, src/main/webapp/WEB-INF/views/flone/class-room-list.jsp, src/main/webapp/WEB-INF/views/flone/classroom-register-form.jsp
- 클래스룸 , 게시판 , 댓글 요청 경로 수정
- controller 와 jsp 내 요청 경로 수정
예시 ) board-detail ->  flone/board/board-detail
- 모든 경로 수정 해야합니다 ,
=> 클래스룸 , 게시판 , 댓글 요청 경로 수정

src/main/java/org/hermez/classroom/board/controller/BoardController.java, src/main/java/org/hermez/classroom/board/dto/BoardListResponse.java, src/main/java/org/hermez/classroom/board/service/BoardService.java, src/main/java/org/hermez/classroom/board/service/impl/BoardServiceImpl.java, src/main/java/org/hermez/classroom/classroom/controller/ClassroomController.java, src/main/java/org/hermez/classroom/classroom/dto/ClassroomRegisterRequest.java, src/main/java/org/hermez/classroom/classroom/mapper/ClassroomMapper.java, src/main/java/org/hermez/classroom/classroom/service/impl/ClassroomServiceImpl.java, src/main/java/org/hermez/classroom/reply/model/Reply.java, src/main/webapp/WEB-INF/views/flone/board-list.jsp, src/main/webapp/WEB-INF/views/flone/classroom-register-form.jsp
- 클래스룸 비디오(zoom or youtube) 링크 추가
- 데이터베이스 classroom colum에 video_link 추가
- 한번에 응답을 위한 boardListResponse 추가 및 관련 mapper, service 추가
- 데이터베이스 수정했습니다 노션 확인 바랍니다.
=> 클래스룸 비디오(zoom or youtube) 링크 추가

src/main/java/org/hermez/paymenthistory/mapper/PaymentHistoryMapper.java, src/main/java/org/hermez/paymenthistory/model/PaymentHistoryRepository.java, src/main/java/org/hermez/paymenthistory/model/impl/PaymentHistoryRepositoryImpl.java, src/main/webapp/WEB-INF/spring/root-context.xml
- feat : 결제 기록 레파지토리/마이바티스 매퍼 추가
- 결제 기록 레파지토리/마이바티스 매퍼 추가
-  root-context.xml
- 변경내용과 같음
=> feat : 결제 기록 레파지토리/마이바티스 매퍼 추가

src/main/java/org/hermez/paymenthistory/mapper/PaymentHistoryMapper.java, src/main/java/org/hermez/paymenthistory/model/PaymentHistoryRepository.java, src/main/java/org/hermez/paymenthistory/model/impl/PaymentHistoryRepositoryImpl.java
- 결제 기록 레파지토리/마이바티스 결제 기록 키값 찾는 메서드 추가
- 결제 기록 레파지토리/마이바티스 결제 기록 키값 찾는 메서드 추가
- 변경 내용과 같음
=> feat : 결제 기록 레파지토리/마이바티스 결제 기록 키값 찾는 메서드 추가

src/main/java/org/hermez/reservation/service/impl/ReservationServiceImpl.java
- reservationService 생성
- reservationService 생성
- 변경 내용과 같음
=> feat : reservationService 생성

src/main/java/org/hermez/reservation/mapper/ReservationMapper.java, src/main/java/org/hermez/reservation/model/ReservationRepository.java, src/main/java/org/hermez/reservation/model/impl/ReservationRepositoryImpl.java, src/main/java/org/hermez/reservation/service/impl/ReservationServiceImpl.java
- reservation 주문 취소 환불 관련 메서드 추가
- reservation 주문 취소 환불 관련 메서드 추가
- 변경내용과 같음
=> feat : reservation 주문 취소 환불 관련 메서드 추가

src/main/java/org/hermez/paymenthistory/mapper/PaymentHistoryMapper.java
- PaymentHistoryMapper.java 버그수정
- PaymentHistoryMapper 버그수정
- 변경 내용과 같음
=> fix : PaymentHistoryMapper.java 버그수정

src/main/java/org/hermez/classroom/reply/controller/ReplyController.java, src/main/java/org/hermez/classroom/reply/dto/ReplyRegisterRequest.java, src/main/java/org/hermez/image/mapper/ImageMapper.java, src/main/java/org/hermez/image/model/Image.java, src/main/java/org/hermez/image/service/impl/ImageServiceImpl.java, src/main/webapp/WEB-INF/views/flone/board-detail.jsp, src/main/webapp/WEB-INF/views/flone/board-list.jsp, src/main/webapp/WEB-INF/views/flone/class-room-list.jsp
- 게시판-댓글-이미지 포맷 변경
- 댓글 위치 변경
- 영상 링크 jsp 변경
- 게시판 이미지 경로 수정
- 댓글 요청/응답 수정
- 이미지 엔티티 생성
- 없습니다!
=> 게시판-댓글-이미지 포맷 변경

src/main/java/org/hermez/reservation/service/ReservationService.java
- reservationservice 추가
- reservationservice 추가
- 변경내용과 같음
=> feat: reservationservice 추가

src/main/java/org/hermez/paymenthistory/model/impl/PaymentHistoryRepositoryImpl.java, src/main/java/org/hermez/reservation/dto/ReservationFormRequest.java, src/main/java/org/hermez/reservation/dto/ReservationFormResponse.java, src/main/java/org/hermez/reservation/dto/VerificationRequest.java, src/main/java/org/hermez/reservation/model/ReservationRepository.java, src/main/java/org/hermez/reservation/model/impl/ReservationRepositoryImpl.java, src/main/java/org/hermez/reservation/service/impl/ReservationServiceImpl.java, src/main/webapp/WEB-INF/views/flone/cancel-payment.jsp, src/main/webapp/WEB-INF/views/flone/complete-payment.jsp, src/main/webapp/WEB-INF/views/flone/payment-detail.jsp
- reservationservice 기능 추가
- reservationservice 기능 추가
- 변경 내용과 같음
=> feature: reservation 기능 추가

src/main/java/org/hermez/paymenthistory/service/payapi/IamportService.java
- IamportService 변경
- IamportService 변경
-
=> refactor: IamportService 변경

src/main/java/org/hermez/classroom/board/exception/BoardServiceException.java, src/main/java/org/hermez/classroom/board/service/impl/BoardServiceImpl.java, src/main/java/org/hermez/classroom/classroom/exception/ClassroomNotFoundException.java, src/main/java/org/hermez/classroom/classroom/mapper/ClassroomMapper.java, src/main/java/org/hermez/classroom/classroom/service/impl/ClassroomServiceImpl.java, src/main/java/org/hermez/classroom/reply/exception/ReplyNotFoundException.java, src/main/java/org/hermez/classroom/reply/mapper/ReplyMapper.java, src/main/java/org/hermez/classroom/reply/service/impl/ReplyServiceImpl.java, src/main/java/org/hermez/common/exception/GlobalExceptionHandler.java, src/main/java/org/hermez/image/exception/ImageProcessingException.java, src/main/java/org/hermez/image/service/impl/ImageServiceImpl.java, src/main/webapp/WEB-INF/views/error.jsp
- 전역 예외 처리 추가
- GlobalExceptionHandler 생성
- Board, Classroom, Image, Reply 예외처리 추가
- GlobalExceptionHandler 사용법 대로 잘 쓰시면 될것 같습니다 !
=> 전역 예외 처리 추가

src/main/java/org/hermez/course/controller/CourseController.java, src/main/webapp/WEB-INF/spring/root-context.xml
- feature/course/control 
- CourseController 추가, root-context 수정 (coursemapper 추가)
-
=> feat: CourseController 추가

src/main/java/org/hermez/classroom/reply/service/impl/ReplyServiceImpl.java
-  불필요한 예외 제거
- 댓글 목록 존재 하지 않을때 예외 제거
- 없습니다.
=>  불필요한 예외 제거

src/main/java/org/hermez/course/controller/CourseController.java, src/main/webapp/WEB-INF/views/flone/course-list.jsp
- feat: course-list.jsp / fix: CourseController
- course-list.jsp 추가 / Controller return 수정
-
=> feat: course-list.jsp 추가

src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/java/org/hermez/reservation/dto/ReservationListResponse.java, src/main/java/org/hermez/reservation/mapper/ReservationMapper.java, src/main/java/org/hermez/reservation/model/ReservationRepository.java, src/main/java/org/hermez/reservation/model/impl/ReservationRepositoryImpl.java, src/main/webapp/WEB-INF/views/flone/header.jsp, src/main/webapp/WEB-INF/views/flone/reservation-list.jsp
- reservation list 추가
- reservation list 추가
- 변경내용 같음
=> feat: reservation list 추가

src/main/webapp/WEB-INF/views/flone/footer.jsp, src/main/webapp/WEB-INF/views/flone/header.jsp, src/main/webapp/WEB-INF/views/flone/index.jsp
- index.jsp css, image / 추가
- header.jsp /flone 추가
- footer.jsp css, image / 추가
=> feat: header, footer, index 경로 수정

src/main/java/org/hermez/member/dto/MemberLoginRequest.java, src/main/webapp/WEB-INF/views/flone/login.jsp
- 로그인 및 세션 설정
- 코드 단순
- login.jsp 추가
- 없습니당.
=> feat: 로그인 및 세션 설정

src/main/java/org/hermez/filter/RoleFilter.java, src/main/webapp/WEB-INF/views/flone/register.jsp, src/main/webapp/WEB-INF/web.xml
- 회원가입 페이지 추가 및 필터 추가
- register.jsp 추가
- RoleFilter.java 추가 (주석)
- web.xml에 RoleFilter 추가
- web.xml에 RoleFilter 추가했습니당.
=> feat: 회원가입 페이지 추가 및 필터 추가

.idea/git_toolbox_prj.xml, src/main/webapp/WEB-INF/views/flone/course-detail.jsp
-fix: course-detail.jsp
- reservation-detail 페이지와 연결
- @tokkaiiii course 관련 entity 참고
=> fix: reservation과 연결

src/main/java/org/hermez/paymenthistory/service/payapi/IamportService.java, src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/java/org/hermez/reservation/mapper/ReservationMapper.java, src/main/java/org/hermez/reservation/model/ReservationRepository.java, src/main/java/org/hermez/reservation/model/impl/ReservationRepositoryImpl.java, src/main/java/org/hermez/reservation/service/impl/ReservationServiceImpl.java, src/main/webapp/WEB-INF/views/flone/reservation-list.jsp
- reservation 환불기능 추가
- reservation 환불기능 추가
- 변경내용과 같음
=> feature: reservation 환불 기능추가

src/main/java/org/hermez/reservation/mapper/ReservationMapper.java, src/main/java/org/hermez/reservation/model/ReservationRepository.java, src/main/java/org/hermez/reservation/model/impl/ReservationRepositoryImpl.java, src/main/webapp/WEB-INF/views/flone/header.jsp
- reservation url 수정 및 reservation 안쓰는 메서드 제거
- reservation url 수정 및 reservation 안쓰는 메서드 제거
- 변경내용과 같음
=> refactor: reservation url 수정 및 reservation 안쓰는 메서드 제거

src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/webapp/WEB-INF/views/flone/payment-detail.jsp, src/main/webapp/WEB-INF/views/flone/reservation-list.jsp
- reservation 강의 내용받을 수 있게 수정
- reservation 강의 내용받을 수 있게 수정
- 변경내용과 같음
=> refactor: reservation 강의 내용받을 수 있게 수정

src/main/java/org/hermez/instructor/controller/InstructorController.java, src/main/java/org/hermez/instructor/dto/InstructorListResponse.java, src/main/java/org/hermez/instructor/mapper/InstructorMapper.java, src/main/java/org/hermez/instructor/model/Instructor.java, src/main/java/org/hermez/instructor/service/InstructorService.java, src/main/java/org/hermez/instructor/service/impl/InstructorServiceImpl.java, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/flone/instructor-details.jsp, src/main/webapp/WEB-INF/views/flone/instructor-list.jsp
- 강사 목록 페이지 구현
---
- Instructor.java
- InstructorController.java
- InstructorListResponse.java
- instructor-list.jsp
- instructor-details.jsp
- root-context.xml (org.hermez.instructor.mapper 추가)
---
- root-context.xml에 추가했습니당.
=> feat: 강사 목록 페이지 구현

src/main/java/org/hermez/course/dto/CourseDetailResponse.java, src/main/java/org/hermez/course/mapper/CourseMapper.java, src/main/java/org/hermez/course/service/impl/CourseServiceImpl.java, src/main/webapp/WEB-INF/views/flone/course-detail.jsp
-강의 예약 오류 수정
-courseId를 받아올 수 있게 수정
-
=> fix: 강의 예약 연결 수정

src/main/java/org/hermez/classroom/classroom/controller/ClassroomController.java, src/main/java/org/hermez/classroom/classroom/mapper/ClassroomMapper.java, src/main/java/org/hermez/classroom/classroom/service/ClassroomService.java, src/main/java/org/hermez/classroom/classroom/service/impl/ClassroomServiceImpl.java, src/main/java/org/hermez/common/exception/GlobalExceptionHandler.java, src/main/java/org/hermez/common/page/Page.java, src/main/java/org/hermez/common/page/PaginationUtil.java, src/main/webapp/WEB-INF/views/flone/class-room-list.jsp
- 페이징 유틸 기능 추가
- Page, PagenationUtil 추가
- 클래스룸카드리스트 Page 적용
- 노션에 정리된거 보시고 적용하시면 문제 없을것 같습니다!
=> 페이징 유틸 기능 추가

pom.xml, src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/java/org/hermez/reservation/dto/MyReservationDTO.java, src/main/java/org/hermez/reservation/exception/NoSuchUniqueCourseTimeException.java, src/main/java/org/hermez/reservation/mapper/ReservationMapper.java, src/main/java/org/hermez/reservation/model/ReservationRepository.java, src/main/java/org/hermez/reservation/model/impl/ReservationRepositoryImpl.java, src/main/java/org/hermez/reservation/service/ReservationService.java, src/main/java/org/hermez/reservation/service/impl/ReservationServiceImpl.java
- reservation 스케쥴링 추가
- reservation 스케쥴링 추가
- pom.xml dependency 추가했으니 로딩 부탁드립니다.
=> refactor: reservation 스케쥴링 추가

src/main/java/org/hermez/paymenthistory/model/PaymentHistory.java, src/main/java/org/hermez/paymenthistory/service/payapi/IamportService.java, src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/java/org/hermez/reservation/dto/ReservationFormRequest.java, src/main/java/org/hermez/reservation/dto/ReservationFormResponse.java, src/main/java/org/hermez/reservation/dto/ReservationListResponse.java, src/main/java/org/hermez/reservation/dto/VerificationRequest.java, src/main/java/org/hermez/reservation/mapper/ReservationMapper.java, src/main/java/org/hermez/reservation/model/ReservationRepository.java, src/main/java/org/hermez/reservation/model/impl/ReservationRepositoryImpl.java, src/main/java/org/hermez/reservation/service/ReservationService.java, src/main/java/org/hermez/reservation/service/impl/ReservationServiceImpl.java, src/main/webapp/WEB-INF/views/flone/payment-detail.jsp
- reservation 스케쥴링 기능
- reservation 스케쥴링 추가
- 변경 내용과 같음
=> feature: reservation 스케쥴링 기능

src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/java/org/hermez/reservation/service/impl/ReservationServiceImpl.java
- reservation 로그 정리
- reservation 로그 정리
- 변경내용과 같음
=> feature: reservation 로그 정리

src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/java/org/hermez/reservation/dto/ReservationListResponse.java, src/main/java/org/hermez/reservation/mapper/ReservationMapper.java, src/main/webapp/WEB-INF/views/flone/complete-payment.jsp, src/main/webapp/WEB-INF/views/flone/payment-detail.jsp, src/main/webapp/WEB-INF/views/flone/reservation-detail.jsp, src/main/webapp/WEB-INF/views/flone/reservation-list.jsp
- reservation 예약 성공시 페이지
- reservation 예약 성공시 페이지
- 변경내용과 같음
=> feature: reservation 예약 성공시 페이지

src/main/java/org/hermez/course/controller/CourseController.java, src/main/java/org/hermez/course/dto/CourseDetailResponse.java, src/main/java/org/hermez/course/dto/CourseListResponse.java, src/main/java/org/hermez/course/dto/CourseRegisterRequest.java, src/main/java/org/hermez/course/mapper/CourseMapper.java, src/main/java/org/hermez/course/service/CourseService.java, src/main/java/org/hermez/course/service/impl/CourseServiceImpl.java, src/main/webapp/WEB-INF/views/flone/course-detail.jsp, src/main/webapp/WEB-INF/views/flone/course-list.jsp, src/main/webapp/WEB-INF/views/flone/course-register.jsp
- 강의 이미지 등록 추가
- course dto에 file parameter 추가 (courseImage)
- view page 이미지 적용
- mapper query문 수정
- service 기능 추가
-  사진 올려서 확인 요망
=> 강의 이미지 등록 기능 추가

src/main/java/org/hermez/reservation/dto/ReservationFormResponse.java
- reservation 가격 데이터타입 int로 변경
- reservation 가격 데이터타입 int로 변경
- 변경내용과 같음
=> refactor: reservation 가격 데이터타입 int로 변경

src/main/java/org/hermez/course/controller/CourseController.java, src/main/java/org/hermez/course/service/CourseService.java, src/main/java/org/hermez/course/service/impl/CourseServiceImpl.java, src/main/webapp/WEB-INF/views/flone/course-list.jsp
- fix: course 등록 후 사진이 보이지 않는 오류 수정
-fix: CourseService - insert 로직 순서 변경 / 리팩토링
-refactor: CourseController - 중복 parameter 변경 및 삭제
-refactor: CourseServiceImpl - 중복 parameter 변경 및 삭제
-refactor: CourseMapper - 중복 parameter 변경 및 삭제
-  테스트 완료 / 확인 부탁드립니다
=> fix: Course 사진 관련 오류 수정

src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/java/org/hermez/reservation/mapper/ReservationMapper.java, src/main/java/org/hermez/reservation/model/ReservationRepository.java, src/main/java/org/hermez/reservation/model/impl/ReservationRepositoryImpl.java, src/main/java/org/hermez/reservation/service/ReservationService.java, src/main/java/org/hermez/reservation/service/impl/ReservationServiceImpl.java, src/main/webapp/WEB-INF/views/flone/reservation-list.jsp
- reservation 예약 리스트 페이지네이션
- reservation 예약 리스트 페이지네이션
- 변경내용과 같음
=> feat: reservation 예약 리스트 페이지네이션

src/main/java/org/hermez/instructor/controller/InstructorController.java, src/main/java/org/hermez/instructor/mapper/InstructorMapper.java, src/main/java/org/hermez/instructor/service/InstructorService.java, src/main/java/org/hermez/instructor/service/impl/InstructorServiceImpl.java, src/main/webapp/WEB-INF/views/flone/instructor-list.jsp
- 강사 페이징
- InstructorController.java
- instructor-list.jsp
- 없습니당.
=> feat: 강사 페이징

src/main/webapp/WEB-INF/views/flone/reservation-list.jsp
- 예약 리스트 페이지 페이지네이션 번호 스타일 변경
- 예약 리스트 페이지 페이지네이션 번호 스타일 변경
- 변경 내용과 같음
=> feature: 예약 리스트 페이지 페이지네이션 번호 스타일 변경

src/main/webapp/WEB-INF/views/flone/cancel-payment.jsp, src/main/webapp/WEB-INF/views/flone/complete-payment.jsp, src/main/webapp/WEB-INF/views/flone/payment-detail.jsp, src/main/webapp/WEB-INF/views/flone/reservation-list.jsp, src/main/webapp/resources/assets/js/cancelpay.js, src/main/webapp/resources/assets/js/reservation.js
- 예약 취소/환불 자바스크립트 파일 따로 만듬
- 예약 취소/환불 자바스크립트 파일 따로 만듬
- 변경 내용과 같음
=> refactor: 예약 취소/환불 자바스크립트 파일 따로 만듬

src/main/java/org/hermez/admin/controller/AdminController.java, src/main/java/org/hermez/admin/dto/CourseReservationRankResponse.java, src/main/java/org/hermez/admin/dto/MonthlyPaymentHistoryResponse.java, src/main/java/org/hermez/admin/dto/MonthlySignupResponse.java, src/main/java/org/hermez/admin/dto/SubjectCourseCountResponse.java, src/main/java/org/hermez/admin/mapper/AdminMapper.java, src/main/java/org/hermez/admin/model/Admin.java, src/main/java/org/hermez/admin/service/AdminService.java, src/main/java/org/hermez/admin/service/impl/AdminServiceImpl.java, src/main/webapp/WEB-INF/spring/root-context.xml, src/main/webapp/WEB-INF/views/flone/admin-footer.jsp, src/main/webapp/WEB-INF/views/flone/admin-header.jsp, src/main/webapp/WEB-INF/views/flone/admin-main.jsp, src/main/webapp/WEB-INF/views/flone/admin-sidebar.jsp
- 관리자 메인 페이지 구현
- admin Main jsp  Mvc 구현
- 회원 통계, 강의 통계, 강사 통계 구현
- mapper 추가했습니다 충돌 날 일은 없도록 하겠습니다!!
=> 관리자 메인 페이지 구현

src/main/webapp/WEB-INF/views/flone/payment-detail.jsp, src/main/webapp/WEB-INF/views/flone/refund-list-payment.jsp, src/main/webapp/WEB-INF/views/flone/refund-payment.jsp, src/main/webapp/WEB-INF/views/flone/reservation-detail.jsp, src/main/webapp/WEB-INF/views/flone/reservation-list.jsp, src/main/webapp/resources/assets/js/cancelpay.js
- 예약 관련 js파일 jps파일로 묶음
- 예약 관련 js파일 jps파일로 묶음
- 변경내용과 같음
=> refactor: 예약 관련 js파일 jps파일로 묶음

src/main/java/org/hermez/common/exception/GlobalExceptionHandler.java, src/main/webapp/WEB-INF/views/flone/error/404.jsp, src/main/webapp/WEB-INF/web.xml
- 404에러페이지 추가
- 404에러페이지 추가
- 변경내용과 같음
=> feature: 404에러페이지 추가

src/main/webapp/WEB-INF/web.xml
- 404에러페이지 설정 수정
- 404에러페이지 설정 수정
- 변경내용과 같음
=> refactor: 404에러페이지 설정 수정

src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/webapp/WEB-INF/views/flone/payment-detail.jsp, src/main/webapp/WEB-INF/views/flone/reservation-detail.jsp, src/main/webapp/WEB-INF/views/flone/reservation-list.jsp
- 예약 상세페이지
- 예약 상세페이지
- 변경내용과 같음
=> feature: 예약 상세페이지

src/main/java/org/hermez/instructor/controller/InstructorController.java, src/main/java/org/hermez/instructor/dto/InstructorDetailResponse.java, src/main/java/org/hermez/instructor/dto/InstructorListResponse.java, src/main/java/org/hermez/instructor/mapper/InstructorMapper.java, src/main/java/org/hermez/instructor/service/InstructorService.java, src/main/java/org/hermez/instructor/service/impl/InstructorServiceImpl.java, src/main/webapp/WEB-INF/views/flone/instructor-detail.jsp, src/main/webapp/WEB-INF/views/flone/instructor-list.jsp
- 강사 상세페이지 구현 및 리스트 수정
- InstructorController.java
- InstructorDetailResponse.java
- InstructorListResponse.java
- instructor-list.jsp
- instructor-detail.jsp
- 없습니다.
=> 강사 상세페이지 구현 및 리스트 수정

src/main/java/org/hermez/instructor/mapper/InstructorMapper.java, src/main/java/org/hermez/instructor/service/InstructorService.java, src/main/java/org/hermez/instructor/service/impl/InstructorServiceImpl.java, src/main/java/org/hermez/member/controller/MemberController.java, src/main/java/org/hermez/member/dto/MemberRegisterRequest.java, src/main/java/org/hermez/member/mapper/MemberMapper.java, src/main/java/org/hermez/member/model/Member.java, src/main/java/org/hermez/member/service/impl/MemberServiceImpl.java, src/main/webapp/WEB-INF/views/flone/header.jsp, src/main/webapp/WEB-INF/views/flone/my-account.jsp, src/main/webapp/WEB-INF/views/flone/register.jsp
- 세션 설정, (공통)헤더 수정, 마이페이지 페이지 추가
- MemberRegisterRequest.java
- Member.java
- register.jsp
- header.jsp
- 헤더를 세션이 있어야 나오게 수정해서 로그인하시고 테스트 하시면 됩니다!
=> 세션 설정, (공통)헤더 수정, 마이페이지 페이지 추가

pom.xml, src/main/java/org/hermez/member/controller/MemberController.java, src/main/webapp/WEB-INF/views/flone/login.jsp
- 소셜 로그인(naver) 기능만 추가
- login.jsp
- pom.xml
- pom.xml 시큐리티, JSON 추가했습니다.
- 소셜 로그인은 테스트만 가능합니다!
=> 소셜 로그인(naver) 기능만 추가

src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/java/org/hermez/reservation/dto/ReservationFormResponse.java
- 예약 회원: 세션 있는 회원으로 변경
- 예약 회원: 세션 있는 회원으로 변경
- 변경내용과 같음
=> feature: 예약 회원: 세션 있는 회원으로 변경

src/main/java/org/hermez/paymenthistory/service/payapi/IamportService.java, src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/java/org/hermez/reservation/dto/MyReservationDTO.java, src/main/java/org/hermez/reservation/dto/MyReservedReservationDTO.java, src/main/java/org/hermez/reservation/mapper/ReservationMapper.java, src/main/java/org/hermez/reservation/model/Reservation.java, src/main/java/org/hermez/reservation/model/ReservationRepository.java, src/main/java/org/hermez/reservation/model/impl/ReservationRepositoryImpl.java, src/main/webapp/WEB-INF/views/flone/complete-payment.jsp, src/main/webapp/WEB-INF/views/flone/my-reservation-list.jsp, src/main/webapp/WEB-INF/views/flone/reservation-detail.jsp
- 예약 관련 뷰 만듬
- 예약 관련 뷰 만듬
- 변경내용과 같음
=> feat: 예약 관련 뷰

src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/java/org/hermez/reservation/exception/NotActiveClassException.java, src/main/java/org/hermez/reservation/service/impl/ReservationServiceImpl.java, src/main/webapp/WEB-INF/views/flone/cancel-payment.jsp
- 강의 시작일이 지난 강의 예약시 exception 추가
- 강의 시작일이 지난 강의 예약시 exception 추가
- 변경내용과 같음
=> feature: 강의 시작일이 지난 강의 예약시 exception 추가

src/main/java/org/hermez/common/exception/GlobalExceptionHandler.java, src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/java/org/hermez/reservation/dto/ReservationListResponse.java, src/main/java/org/hermez/reservation/model/Reservation.java, src/main/webapp/WEB-INF/views/flone/my-reservation-list.jsp, src/main/webapp/WEB-INF/views/flone/reservation-list.jsp, src/main/webapp/resources/assets/js/reservation.js
- 수강 시작일 지난 강의 예약시 예외 처리
- 수강 시작일 지난 강의 예약시 예외 처리
- 변경내용과 같음
=> feature: 수강 시작일 지난 강의 예약시 예외 처리

src/main/java/org/hermez/reservation/mapper/ReservationMapper.java, src/main/java/org/hermez/reservation/model/ReservationRepository.java, src/main/java/org/hermez/reservation/model/impl/ReservationRepositoryImpl.java
- 모든 회원의 예약 리스트 목록 & 모든 회원의 환불/취소 목록
- 모든 회원의 예약 리스트 목록 & 모든 회원의 환불/취소 목록 repository, mapper 작성
- 변경내용과 같음
=> feat: 모든 회원의 예약 리스트 목록 & 모든 회원의 환불/취소 목록

src/main/java/org/hermez/reservation/service/ReservationService.java, src/main/java/org/hermez/reservation/service/impl/ReservationServiceImpl.java
- 예약 목록 및 환불 전체 조회 서비스 작성
- 예약 목록 및 환불 전체 조회 서비스 작성
- 변경내용과 같음
=> feat: 예약 목록 및 환불 전체 조회 서비스 작성

src/main/java/org/hermez/image/mapper/ImageMapper.java, src/main/java/org/hermez/image/service/ImageService.java, src/main/java/org/hermez/image/service/impl/ImageServiceImpl.java
- 이미지 단건 조회 서비스 구현
- 이미지 서비스, 매퍼 변경
- getSaveImage(id,type) 구현
- 따로 노션에 사용법 적진 않을게요~
=> 이미지 단건 조회 서비스 구현

src/main/java/org/hermez/member/controller/MemberController.java, src/main/java/org/hermez/member/dto/MyAccountEditRequest.java, src/main/java/org/hermez/member/mapper/MemberMapper.java, src/main/java/org/hermez/member/service/MemberService.java, src/main/java/org/hermez/member/service/impl/MemberServiceImpl.java, src/main/webapp/WEB-INF/views/flone/my-account.jsp
- 마이페이지 수정 구현
- MyAccountEditRequest.java
- MyAccountResponse.java
- MemberService.java
- 없습니당.
=> 마이페이지 수정 구현

src/main/java/org/hermez/instructor/mapper/InstructorMapper.java, src/main/java/org/hermez/instructor/service/InstructorService.java, src/main/java/org/hermez/instructor/service/impl/InstructorServiceImpl.java, src/main/java/org/hermez/member/controller/MemberController.java, src/main/java/org/hermez/member/dto/MemberLoginResponse.java, src/main/java/org/hermez/member/exception/MemberServiceException.java, src/main/java/org/hermez/member/mapper/MemberMapper.java, src/main/java/org/hermez/member/service/impl/MemberServiceImpl.java, src/main/webapp/WEB-INF/views/flone/header.jsp
- 로그인 유효성 구현 및 예외처리
- MemberLoginResponse.java
- MemberServiceException.java
- header.jsp
- header에 마이페이지 들어갈 때 memberId 넣었습니당.
=> 로그인 유효성 구현 및 예외처리

src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/java/org/hermez/reservation/dto/MyPaymentDetailResponse.java, src/main/java/org/hermez/reservation/mapper/ReservationMapper.java, src/main/java/org/hermez/reservation/model/ReservationRepository.java, src/main/java/org/hermez/reservation/model/impl/ReservationRepositoryImpl.java, src/main/java/org/hermez/reservation/service/impl/ReservationServiceImpl.java, src/main/webapp/WEB-INF/views/flone/my-payment-detail.jsp, src/main/webapp/WEB-INF/views/flone/payment-detail.jsp, src/main/webapp/WEB-INF/views/flone/reservation-list.jsp
- 결제 상세 페이지 추가
- 결제 상세 페이지 추가
- 변경내용과 같음
=> feat: 결제 상세 페이지 추가

src/main/java/org/hermez/reservation/controller/ReservationController.java
- 세션 받는법 수정
- 세션 받는법 수정
- 변경내용과 같음
=> refactor: 세션 받는법 수정

src/main/webapp/WEB-INF/views/flone/header.jsp
- 헤더에 나의 강의 추가
- 헤더에 나의 강의 추가
-
=> feat: 헤더에 나의 강의 추가

src/main/webapp/WEB-INF/views/flone/my-account.jsp
=> 마이페이지 디자인 수정

src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/webapp/WEB-INF/views/flone/payment-detail.jsp
- 세션 받는법 수정 & 결제 페이지 수정
- 세션 받는법 수정 & 결제 페이지 수정
- 변경내용과 같음
=> refactor: 세션 받는법 수정 & 결제 페이지 수정

src/main/webapp/WEB-INF/views/flone/login.jsp, src/main/webapp/WEB-INF/views/flone/my-account.jsp, src/main/webapp/WEB-INF/views/flone/register.jsp, src/main/webapp/resources/assets/js/toggleVisibility.js
- 비밀번호 가시성 버튼 추가
- login.jsp
- register.jsp
- toggleVisibility.js
- 없습니당.
=> 비밀번호 가시성 버튼 추가

src/main/java/org/hermez/member/controller/MemberController.java, src/main/java/org/hermez/member/mapper/MemberMapper.java, src/main/java/org/hermez/member/service/impl/MemberServiceImpl.java, src/main/webapp/WEB-INF/views/flone/register.jsp, src/main/webapp/resources/assets/js/toggleVisibility.js
- 회원가입 유효성 추가
- register.jsp
- toggleVisibility.js (번호 입력 자동 하이퍼 추가)
- 없습니다!
=> 회원가입 유효성 추가

src/main/java/org/hermez/member/mapper/MemberMapper.java, src/main/java/org/hermez/member/service/impl/MemberServiceImpl.java
- 로그인 암호화 주석처리
- 회원가입한 후 암호화된 걸로 로그인을 해야 해서, 암호화 구현은 했고, 코드는 주석 처리했습니다.
=> 로그인 암호화 주석처리

src/main/java/org/hermez/course/controller/CourseController.java, src/main/java/org/hermez/course/dto/CourseListResponse.java, src/main/java/org/hermez/course/mapper/CourseMapper.java, src/main/java/org/hermez/course/model/Course.java, src/main/java/org/hermez/course/service/CourseService.java, src/main/java/org/hermez/course/service/impl/CourseServiceImpl.java, src/main/webapp/WEB-INF/views/flone/course-detail.jsp
- 카테고리 별 강좌목록 서비스 구현
- service 기능 구현
- mapper 추가 기능용 query문 추가
- controller 통합
- course-list, course-detail에 링크 추가
- 문제있으면 알려주세요
=> 카테고리 별 강좌목록 서비스 구현

src/main/webapp/WEB-INF/views/flone/login.jsp
- 로그인 페이지 수정
- login.jsp
- 없습니당.
=> 로그인 페이지 수정

src/main/java/org/hermez/admin/controller/AdminCourseController.java, src/main/java/org/hermez/admin/controller/AdminInstructorController.java, src/main/java/org/hermez/admin/controller/AdminMemberController.java, src/main/java/org/hermez/admin/controller/AdminPaymentController.java, src/main/java/org/hermez/admin/dto/InstructorManageListResponse.java, src/main/java/org/hermez/admin/mapper/AdminMapper.java, src/main/java/org/hermez/admin/service/AdminService.java, src/main/java/org/hermez/admin/service/impl/AdminServiceImpl.java, src/main/java/org/hermez/classroom/classroom/service/ClassroomService.java, src/main/java/org/hermez/instructor/controller/InstructorController.java, src/main/java/org/hermez/instructor/service/impl/InstructorServiceImpl.java, src/main/webapp/WEB-INF/views/flone/admin-course.jsp, src/main/webapp/WEB-INF/views/flone/admin-header.jsp, src/main/webapp/WEB-INF/views/flone/admin-instructor-list.jsp, src/main/webapp/WEB-INF/views/flone/admin-instructor-register.jsp, src/main/webapp/WEB-INF/views/flone/admin-main.jsp, src/main/webapp/WEB-INF/views/flone/admin-member.jsp, src/main/webapp/WEB-INF/views/flone/admin-payment.jsp, src/main/webapp/WEB-INF/views/flone/admin-refund.jsp, src/main/webapp/WEB-INF/views/flone/admin-sidebar.jsp, src/main/webapp/WEB-INF/views/flone/chart-payment.jsp, src/main/webapp/WEB-INF/views/flone/chart-refund.jsp, src/main/webapp/WEB-INF/views/flone/chart-signup.jsp
- 관리자 페이지 추가 기능 구현
- 관리자 페이지 레이아웃 변경
- 헤더 사이드바 링크 변경
- 관리자 멤버페이지 추가구현
- 관리자 각 페이지 ( service는 구현 x ) 구현
- 불필요한 import 제거
- jsp 통계 분산화
- contoller 분산화
jsp를 통계별로 나눠서 분산해서 저장했습니다. 다른곳에서도 사용 가능해요.
관리자 멤버와 강사는 구현이 어느정도 되었는데 결제 및 환불이 아직 미구현 입니다.
오늘안에 끝내겠습니다!
=> 관리자 페이지 추가 기능 구현

src/main/java/org/hermez/course/controller/CourseController.java, src/main/java/org/hermez/course/mapper/CourseMapper.java, src/main/java/org/hermez/course/service/CourseService.java, src/main/java/org/hermez/course/service/impl/CourseServiceImpl.java, src/main/webapp/WEB-INF/views/flone/course-detail.jsp, src/main/webapp/WEB-INF/views/flone/course-register.jsp
- 강의 업로드 추가/수정
- 강의 업로드 페이지 시간대 추가 제거 기능 추가
- 컨트롤러 세션, id값 받아오는 기능 추가
- 매퍼 query문 추가 및 삭제
- instructorId를 받아오는 기능 추가
- 강의 상세보기 주석 삭제
- 확인 요망
=> 강의 업로드 추가/수정

src/main/java/org/hermez/admin/controller/AdminCourseController.java, src/main/java/org/hermez/admin/dto/CourseManageListResponse.java, src/main/java/org/hermez/admin/mapper/AdminMapper.java, src/main/java/org/hermez/admin/service/AdminService.java, src/main/java/org/hermez/admin/service/impl/AdminServiceImpl.java, src/main/webapp/WEB-INF/views/flone/admin-course-detail.jsp, src/main/webapp/WEB-INF/views/flone/admin-course.jsp, src/main/webapp/WEB-INF/views/flone/admin-sidebar.jsp
- 관리자 페이지에서 강의 리스트 및 강의 상세페이지 구현
- 관리자 사이드바 링크 변경
- 강의 리스트(예약전, 진행중, 종료) 페이징 적용
- 관리자 강의 상세페이지 적용 
- 오늘안에 관리자 페이지 끝내겠습니다!
=> 관리자 페이지에서 강의 리스트 및 강의 상세페이지 구현

src/main/java/org/hermez/admin/controller/AdminPaymentController.java, src/main/java/org/hermez/admin/dto/AdminMainResponse.java, src/main/java/org/hermez/admin/service/AdminService.java, src/main/java/org/hermez/admin/service/impl/AdminServiceImpl.java, src/main/java/org/hermez/classroom/classroom/mapper/ClassroomMapper.java, src/main/java/org/hermez/classroom/classroom/service/ClassroomService.java, src/main/java/org/hermez/classroom/classroom/service/impl/ClassroomServiceImpl.java, src/main/webapp/WEB-INF/views/flone/admin-course-detail.jsp, src/main/webapp/WEB-INF/views/flone/admin-header.jsp, src/main/webapp/WEB-INF/views/flone/admin-instructor-register.jsp, src/main/webapp/WEB-INF/views/flone/admin-main.jsp, src/main/webapp/WEB-INF/views/flone/admin-member.jsp, src/main/webapp/WEB-INF/views/flone/admin-payment-detail.jsp, src/main/webapp/WEB-INF/views/flone/admin-payment.jsp, src/main/webapp/WEB-INF/views/flone/admin-refund.jsp, src/main/webapp/WEB-INF/views/flone/chart-payment.jsp, src/main/webapp/WEB-INF/views/flone/chart-refund.jsp
- 관리자 페이지 예약 및 결제, 레이아웃 추가 기능 구현
- 강의 상세페이지 수정
- 관리자 메인 페이지 클래스룸 조회
- 결제 및 환불 리스트 조회
- 없습니다
=> 관리자 페이지 예약 및 결제, 레이아웃 추가 기능 구현

src/main/java/org/hermez/oauth/exception/OauthServiceException.java
- 소셜 로그인 예외 추가
- OauthServiceException.java
- 없습니다!
=> 소셜 로그인 예외 추가

src/main/java/org/hermez/common/util/EmailService.java
- 이메일 서비스 작성
- 이메일 서비스 작성
- 변경내용과 같음
=> 이메일 서비스 작성

src/main/java/org/hermez/reservation/mapper/ReservationMapper.java, src/main/java/org/hermez/reservation/model/ReservationRepository.java, src/main/java/org/hermez/reservation/model/impl/ReservationRepositoryImpl.java, src/main/java/org/hermez/reservation/service/ReservationService.java, src/main/java/org/hermez/reservation/service/impl/ReservationServiceImpl.java
- reservation mapper 강의조건으로 예약리스트 가져오는 메서드 추가
- reservation mapper 강의조건으로 예약리스트 가져오는 메서드 추가
- 변경내용과 같음
=> reservation mapper 강의조건으로 예약리스트 가져오는 메서드 추가

src/main/java/org/hermez/common/exception/GlobalExceptionHandler.java, src/main/java/org/hermez/course/mapper/CourseMapper.java, src/main/java/org/hermez/course/service/CourseService.java, src/main/java/org/hermez/course/service/impl/CourseServiceImpl.java
-강의 예약 시간과 관련 예외처리
-시간 관련 예외처리 로직 추가
-이미지 처리에 문제있던 Query문 수정
-전체 강의 수를 불러오는 Query문 추가
-Global Excepiton Handler에 강의관련 Exception 추가
- @HS-hyeokjin 요청사항 적용했습니다
=> 강의 예약 시간관련 예외처리 외

src/main/java/org/hermez/course/exception/CourseRegisterTimeException.java
- feat: 강의 예약 시간 중복처리
- exception 안올렸던거 추가
-
=> feat: 강의 예약 시간 중복처리

pom.xml
- pom.xml 이메일 관련 dependency 추가
- pom.xml 이메일 관련 dependency 추가
- 변경내용과 같음
=> pom.xml 이메일 관련 dependency 추가

src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/java/org/hermez/reservation/mapper/ReservationMapper.java, src/main/java/org/hermez/reservation/model/ReservationRepository.java, src/main/java/org/hermez/reservation/model/impl/ReservationRepositoryImpl.java
- reservationMapper 수정
- reservationMapper 수정
- 변경내용과 같음
=> reservationMapper 수정

src/main/java/org/hermez/admin/controller/AdminMemberController.java, src/main/java/org/hermez/admin/controller/AdminPaymentController.java, src/main/java/org/hermez/admin/dto/CourseReservationRankResponse.java, src/main/java/org/hermez/admin/model/Admin.java, src/main/java/org/hermez/admin/service/AdminService.java, src/main/java/org/hermez/admin/service/impl/AdminServiceImpl.java, src/main/java/org/hermez/member/service/impl/MemberServiceImpl.java, src/main/java/org/hermez/reservation/model/impl/ReservationRepositoryImpl.java, src/main/webapp/WEB-INF/views/flone/admin-main.jsp, src/main/webapp/WEB-INF/views/flone/admin-member-detail.jsp
- 관리자 멤버관리 상세페이지 추가
- 관리자 멤버관리 상세페이지 추가
- import, entity, dto 쓰이지 않는것 제거
- 없습니다.
=> 관리자 멤버관리 상세페이지 추가 및 불필요한 데이터 제거

src/main/java/org/hermez/reservation/controller/ReservationController.java
- ReservationController 코드수정
- ReservationController 코드수정
- 변경내용과 같음
=> ReservationController 코드수정

src/main/java/org/hermez/member/controller/MemberController.java, src/main/java/org/hermez/member/mapper/MemberMapper.java, src/main/java/org/hermez/member/model/Member.java
- 회원가입 및 로그인 오류 수정
- Member.java
- 고쳤어요 ㅠㅠ
=> 회원가입 및 로그인 오류 수정

src/main/java/org/hermez/member/controller/MemberController.java, src/main/webapp/WEB-INF/views/flone/my-account.jsp
=> 회원 상태 변경 구현

src/main/java/org/hermez/course/mapper/CourseMapper.java
- 강의 사진과 관련된 오류를 수정합니다
-mapper의 이미지관련 sql 수정
- 오류있으면 알려주세요.
=> fix : 강의 사진관련 오류 수정

src/main/java/org/hermez/admin/controller/AdminMemberController.java, src/main/java/org/hermez/admin/mapper/AdminMapper.java, src/main/java/org/hermez/admin/service/impl/AdminServiceImpl.java, src/main/java/org/hermez/instructor/service/impl/InstructorServiceImpl.java, src/main/webapp/WEB-INF/views/flone/admin-main.jsp, src/main/webapp/WEB-INF/views/flone/admin-member-detail.jsp, src/main/webapp/WEB-INF/views/flone/admin-member.jsp, src/main/webapp/WEB-INF/views/flone/admin-sidebar.jsp
- 관리자 멤버 상세페이지 기능 추가
- 관리자 멤버 상세 페이지 구현
- 관련 링크 및 컨트롤러 요청 경로 변ㅂ경
- 없습니다
=> 관리자 멤버 상세페이지 기능 추가

src/main/java/org/hermez/member/controller/MemberController.java, src/main/java/org/hermez/member/mapper/MemberMapper.java, src/main/java/org/hermez/member/service/impl/MemberServiceImpl.java, src/main/webapp/WEB-INF/views/flone/my-account.jsp, src/main/webapp/WEB-INF/views/flone/register.jsp
- 비회원 로그인 제한 구현
- register.jsp
- 탈퇴 신청한 비회원은 로그인 하지 못합니다.
=> 비회원 로그인 제한 구현

src/main/java/org/hermez/image/service/impl/ImageServiceImpl.java, src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/webapp/WEB-INF/views/flone/reservation-detail.jsp
- 이미지 저장 경로 및 클래스룸 리스트
- 이미지 경로를 target 으로 변경
- 클래스룸 리스트 4장만 예약 강의에서 가져오기
테스트는 상범님께 부탁하겠습니다!
=> 이미지 저장 경로 및 클래스룸 리스트

src/main/java/org/hermez/classroom/classroom/mapper/ClassroomMapper.java, src/main/webapp/WEB-INF/views/flone/reservation-detail.jsp
- 클래스룸 이미지 수정
- 클래스룸 리스트 이미지 조건 추가 및 사이즈 변경
테스트 완료
=> 클래스룸 이미지 수정

src/main/java/org/hermez/course/service/impl/CourseServiceImpl.java, src/main/webapp/WEB-INF/views/flone/course-register.jsp, src/main/webapp/resources/assets/js/addselect.js
- 강의 등록 예외처리 로직 수정
- 강의 등록시 같은 요일에 겹치는 시간대에 예약하지 못하게 로직 수정
- 화이팅
=> fix: 강의 등록 예외처리 로직 수정

src/main/webapp/WEB-INF/views/flone/header.jsp
- 헤더 카테고리별 링크 수정
- 헤더의 카테고리별 링크 수정
-
=> fix : 헤더 카테고리 링크 수정

src/main/java/org/hermez/reservation/controller/ReservationController.java, src/main/java/org/hermez/reservation/service/ReservationService.java, src/main/java/org/hermez/reservation/service/impl/ReservationServiceImpl.java
- ReservationService 강의스케쥴 관련 메서드 파라미터 수정
- ReservationService 강의스케쥴 관련 메서드 파라미터 수정
- 변경내용 없음
=> ReservationService 강의스케쥴 관련 메서드 파라미터 수정

src/main/java/org/hermez/reservation/mapper/ReservationMapper.java
- ReservationMapper sql 수정
- ReservationMapper sql 수정
- 변경내용과 같음
=> ReservationMapper sql 수정

src/main/webapp/WEB-INF/views/flone/instructor-detail.jsp
- 강사 상세페이지 css 수정
- instructor-detail.jsp
- 없습니당.
=> 강사 상세페이지 css 수정

src/main/webapp/WEB-INF/views/flone/header.jsp
- 헤더 수정 및 로고 등록
- header.jsp
- /resources/assets/img/logo/ 여기 안에 슬랙 이미지 넣어주시면 됩니다.
=> 헤더 수정 및 로고 등록

src/main/java/org/hermez/member/controller/MemberController.java, src/main/java/org/hermez/member/dto/MemberCheckPasswordRequest.java, src/main/java/org/hermez/member/dto/MemberCheckPasswordResponse.java, src/main/java/org/hermez/member/mapper/MemberMapper.java, src/main/java/org/hermez/member/service/MemberService.java, src/main/java/org/hermez/member/service/impl/MemberServiceImpl.java, src/main/webapp/WEB-INF/views/flone/password-edit-form.jsp
- 비밀번호 변경 구현
- MemberService.java
- MemberCheckPasswordRequest.java
- MemberCheckPasswordResponse.java
- login.jsp
- password-edit-form.jsp
- 없습니다.
=> 비밀번호 변경 구현

src/main/java/org/hermez/admin/controller/AdminCourseController.java, src/main/java/org/hermez/admin/controller/AdminPaymentController.java, src/main/java/org/hermez/admin/service/AdminService.java, src/main/java/org/hermez/admin/service/impl/AdminServiceImpl.java, src/main/java/org/hermez/classroom/classroom/mapper/ClassroomMapper.java, src/main/webapp/WEB-INF/views/flone/admin-course-detail.jsp, src/main/webapp/WEB-INF/views/flone/admin-member-detail.jsp, src/main/webapp/WEB-INF/views/flone/admin-payment.jsp, src/main/webapp/WEB-INF/views/flone/admin-refund.jsp, src/main/webapp/WEB-INF/views/flone/board-detail.jsp, src/main/webapp/WEB-INF/views/flone/board-list.jsp, src/main/webapp/WEB-INF/views/flone/class-room-list.jsp
- 관리자 결제 상세페이지 구현
- 관리자 결제 상세페이지 구현
- 게시글 접근 방식 변경
- 없습니다~!
=> 관리자 결제 상세페이지 구현

src/main/java/org/hermez/admin/controller/AdminMemberController.java, src/main/webapp/WEB-INF/views/flone/admin-member-detail.jsp
- 관리자 페이지에서 회원 화불 구현
- 관리자 페이지 예약 리스트에서 결제 리스트로 변경
- 없습니다.
=> 관리자페이지 회원 환불 구현

src/main/java/org/hermez/course/controller/CourseController.java, src/main/java/org/hermez/course/dto/CourseDetailResponse.java, src/main/java/org/hermez/course/dto/CourseListResponse.java, src/main/java/org/hermez/course/dto/CourseRegisterRequest.java, src/main/java/org/hermez/course/exception/CourseRegisterTimeException.java, src/main/java/org/hermez/course/mapper/CourseMapper.java, src/main/java/org/hermez/course/model/CourseTime.java, src/main/java/org/hermez/course/service/CourseService.java, src/main/java/org/hermez/course/service/impl/CourseServiceImpl.java, src/main/webapp/WEB-INF/views/flone/course-list.jsp
- Docs: Course의 docs 추가, 수정
- course의 docs 전부 추가, 수정
- course-list.jsp페이지 링크 수정
- 화이팅
=> docs: Course의 docs 추가, 수정

src/main/java/org/hermez/admin/controller/AdminCourseController.java, src/main/java/org/hermez/admin/controller/AdminInstructorController.java, src/main/java/org/hermez/admin/controller/AdminMainController.java, src/main/java/org/hermez/admin/controller/AdminMemberController.java, src/main/java/org/hermez/admin/controller/AdminPaymentController.java, src/main/java/org/hermez/admin/mapper/AdminMapper.java, src/main/java/org/hermez/admin/service/AdminService.java, src/main/java/org/hermez/admin/service/impl/AdminServiceImpl.java, src/main/java/org/hermez/classroom/board/dto/BoardListResponse.java, src/main/java/org/hermez/classroom/classroom/exception/ClassroomNotFoundException.java, src/main/java/org/hermez/classroom/classroom/mapper/ClassroomMapper.java, src/main/java/org/hermez/classroom/classroom/service/ClassroomService.java, src/main/java/org/hermez/classroom/classroom/service/impl/ClassroomServiceImpl.java, src/main/java/org/hermez/common/exception/GlobalExceptionHandler.java, src/main/java/org/hermez/common/page/Page.java, src/main/java/org/hermez/common/page/PaginationUtil.java, src/main/java/org/hermez/filter/RoleFilter.java, src/main/java/org/hermez/filter/exception/AdminFilterException.java, src/main/java/org/hermez/image/exception/ImageProcessingException.java, src/main/java/org/hermez/image/mapper/ImageMapper.java, src/main/java/org/hermez/image/model/Image.java, src/main/java/org/hermez/image/service/ImageService.java, src/main/java/org/hermez/image/service/impl/ImageServiceImpl.java
- 관리자, 클래스룸, 댓글, 유틸, 게시판 JavaDocs 작성
- 관리자 서비스, 클래스룸, 게시판, 답글 서비스에 javadoc 작성
- 노션 작성 양식에 따라 잘 작성해 주세요
=> 관리자, 클래스룸, 댓글, 유틸, 게시판 JavaDocs 작성
